name: DiTo Skynet Pipeline

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      - name: Build webapp
        run: yarn build

      - name: Deploy to Skynet
        uses: kwypchlo/deploy-to-skynet-action@main
        with:
          upload-dir: out
          github-token: ${{ secrets.GITHUB_TOKEN }}
